#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=99
USE_PROCD=1

log() {
	logger -t "WatchDog" "$@"
}

start_service()
{
	echo none > /sys/class/leds/green:signal/trigger
	echo 0  > /sys/class/leds/green:signal/brightness
}
