#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=50
USE_PROCD=1

log() {
	logger -t "WatchDog" "$@"
}

start_service()
{
	usb=$(uci -q get usb.usb.usb)
	echo "$usb" > /sys/class/gpio/ext-usb/value
}
